title = "벧엘선교교회"
baseURL = "https://younghungo.github.io/bmc.github.io/"
languageCode = "ko-kr"
theme = ["gohugo-theme-ananke"]
resourceDir = "../resources"

DefaultContentLanguage = "en"
SectionPagesMenu = "main"
Paginate = 3 # this is set low for demonstrating with dummy content. Set to a higher number
googleAnalytics = ""
enableRobotsTXT = true

[languages]
  [languages.en]
    title = "벧엘선교교회"
    weight = 10
    #contentDir = "content/en"
    # languageDirection = 'rtl' for Right-To-Left languages
  #[languages.fr]
  # title = "벧엘선교교회"
  # weight = 2


[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  text_color = ""
  author = ""
  favicon = ""
  site_logo = "img/bmc_logo.png"
  description = "The last theme you'll ever need. Maybe."
  # choose a background color from any on this page: https://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-white"
  recent_posts_number = 3


